import type { Metadata } from 'next';
import { Montserrat as font, Geist_Mono as fontMono } from 'next/font/google';
import './globals.css';

const Font = font({
	variable: '--font-sans',
	subsets: ['latin'],
});

const FontMono = fontMono({
	variable: '--font-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pt-br'>
			<body className={`${Font.variable} ${FontMono.variable} antialiased`}>{children}</body>
		</html>
	);
}
